export type NationCodeMap = { [key: string]: string };
export const nationCodeMap = {
	INA: "Indonesia",
	MAS: "Malaysia",
	DEN: "Denmark",
	JPN: "Japan",
	CHN: "China",
	TPE: "Taiwan",
	IND: "India",
	HKG: "Hong Kong",
	NED: "Netherlands",
	KOR: "Korea (Republic of)",
	THA: "Thailand",
	ENG: "GB",
	SGP: "Singapore",
	FRA: "France",
	USA: "United States of America",
	ESP: "Spain",
	CAN: "Canada",
	SCO: "Scotland",
	RUS: "Russian Federation",
	GER: "Germany",
	BUL: "Bulgaria",
	AUS: "Australia",
};
